GET http://localhost:4000/api/friendLists/

###

GET http://localhost:4000/api/friendLists/123412341234

###

GET http://localhost:4000/api/friendLists/5d812aa136091e6a2229b31a

###

POST http://localhost:4000/api/friendLists
content-type: application/json

{
    "friendList": [1,2],
    "friendRequests": [1]
}