GET http://localhost:4000/api/locations/

###

GET http://localhost:4000/api/locations/123412341234

###

GET http://localhost:4000/api/locations/5d8114b20bdc0f4d0d0304a6

###

POST http://localhost:4000/api/locations
content-type: application/json

{
    "lat": "43.1",
    "lng": "22.44"
}