GET http://localhost:4000/api/userCards/

###

GET http://localhost:4000/api/userCards/123412341234

###

GET http://localhost:4000/api/userCards/5d810854971e333aa1417484

###

POST http://localhost:4000/api/UserCards
content-type: application/json

{
    "name": "marco2"
}