POST http://localhost:4000/api/auth/register
content-type: application/json

{
    "username": "marco",
    "password": "hi"
}

### 

POST http://localhost:4000/api/auth/login
content-type: application/json

{
    "username": "marco",
    "password": "hi1"
}

###

GET http://localhost:4000/api/auth/logout