GET http://localhost:4000/api/userDetails/

###

GET http://localhost:4000/api/userDetails/123412341234

###

GET http://localhost:4000/api/userDetails/5d812369ec9d906279845aea

###

POST http://localhost:4000/api/userDetails
content-type: application/json

{
    "about": "hi",
    "availableEquipment": ["70m Rope"],
    "languagesSpoken":["Italian"],
    "climbingStyles": ["Lead"]
}